/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ConfigExamsExamIdImport } from './routes/config/exams/$examId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ConfigExamsIndexLazyImport = createFileRoute('/config/exams/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ConfigExamsIndexLazyRoute = ConfigExamsIndexLazyImport.update({
  path: '/config/exams/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/config/exams/index.lazy').then((d) => d.Route),
)

const ConfigExamsExamIdRoute = ConfigExamsExamIdImport.update({
  path: '/config/exams/$examId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/config/exams/$examId': {
      preLoaderRoute: typeof ConfigExamsExamIdImport
      parentRoute: typeof rootRoute
    }
    '/config/exams/': {
      preLoaderRoute: typeof ConfigExamsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ConfigExamsExamIdRoute,
  ConfigExamsIndexLazyRoute,
])

/* prettier-ignore-end */
