/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResultsIndexImport } from './routes/results/index'
import { Route as ExamsIndexImport } from './routes/exams/index'
import { Route as ExamsExamIdImport } from './routes/exams/$examId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ResultsIndexRoute = ResultsIndexImport.update({
  path: '/results/',
  getParentRoute: () => rootRoute,
} as any)

const ExamsIndexRoute = ExamsIndexImport.update({
  path: '/exams/',
  getParentRoute: () => rootRoute,
} as any)

const ExamsExamIdRoute = ExamsExamIdImport.update({
  path: '/exams/$examId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exams/$examId': {
      preLoaderRoute: typeof ExamsExamIdImport
      parentRoute: typeof rootRoute
    }
    '/exams/': {
      preLoaderRoute: typeof ExamsIndexImport
      parentRoute: typeof rootRoute
    }
    '/results/': {
      preLoaderRoute: typeof ResultsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ExamsExamIdRoute,
  ExamsIndexRoute,
  ResultsIndexRoute,
])

/* prettier-ignore-end */
